ready_moves = {
  [1] = {id=1,name="Foul Waters",cost=2,pet="FluffyBredo"},
  [2] = {id=2,name="Pestilent Plume",cost=2,pet="FluffyBredo"},
  [3] = {id=3,name="Molting Plumage",cost=1,pet="SwoopingZhivago"},
  [4] = {id=4,name="Swooping Frenzy",cost=2,pet="SwoopingZhivago"},
  [5] = {id=5,name="Pentapeck",cost=3,pet="SwoopingZhivago"},
  [6] = {id=6,name="Power Attack",cost=1,pet="EnergizedSefina"},
  [7] = {id=7,name="High-Frequency Field",cost=2,pet="EnergizedSefina"},
  [8] = {id=8,name="Rhino Attack",cost=1,pet="EnergizedSefina"},
  [9] = {id=9,name="Rhino Guard",cost=1,pet="EnergizedSefina"},
  [10] = {id=10,name="Spoil",cost=1,pet="EnergizedSefina"},
  [11] = {id=11,name="Purulent Ooze",cost=2,pet="GenerousArthur"},
  [12] = {id=12,name="Corrosive Ooze",cost=3,pet="GenerousArthur"},
  [13] = {id=13,name="Nihility Song",cost=1,pet="DaringRoland"},
  [14] = {id=14,name="Hoof Volley",cost=3,pet="DaringRoland"},
  [15] = {id=15,name="Fantoid",cost=2,pet="DaringRoland"},
  [16] = {id=16,name="Choke Breath",cost=1,pet="DaringRoland"},
  [17] = {id=17,name="Jettatura",cost=3,pet="DaringRoland"},
  [18] = {id=18,name="Back Heel",cost=1,pet="DaringRoland"},
  [19] = {id=19,name="Bubble Shower",cost=1,pet="JovialEdwin"},
  [20] = {id=20,name="Bubble Curtain",cost=2,pet="JovialEdwin"},
  [21] = {id=21,name="Scissor Guard",cost=2,pet="JovialEdwin"},
  [22] = {id=22,name="Metallic Body",cost=1,pet="JovialEdwin"},
  [23] = {id=23,name="Big Scissors",cost=1,pet="JovialEdwin"},
  [24] = {id=24,name="Lamb Chop",cost=1,pet="RhymingShizuna"},
  [25] = {id=25,name="Rage",cost=2,pet="RhymingShizuna"},
  [26] = {id=26,name="Sheep Charge",cost=1,pet="RhymingShizuna"},
  [27] = {id=27,name="Sheep Song",cost=2,pet="RhymingShizuna"},
  [28] = {id=28,name="Chaotic Eye",cost=1,pet="VivaciousGaston"},
  [29] = {id=29,name="Blaster",cost=2,pet="VivaciousGaston"},
  [30] = {id=30,name="Sweeping Gouge",cost=1,pet="VivaciousVickie"},
  [31] = {id=31,name="Zealous Snort",cost=3,pet="VivaciousVickie"},
  [32] = {id=32,name="Sensilla Blades",cost=1,pet="BouncingBertha"},
  [33] = {id=33,name="Tegmina Buffet",cost=2,pet="BouncingBertha"},
  [34] = {id=34,name="Fluid Toss",cost=1,pet="SultryPatrice"},
  [35] = {id=35,name="Fluid Spread",cost=2,pet="SultryPatrice"},
  [36] = {id=36,name="Digest",cost=1,pet="SultryPatrice"},
  [37] = {id=37,name="Suction",cost=1,pet="FatsoFargann"},
  [38] = {id=38,name="Drainkiss",cost=1,pet="FatsoFargann"},
  [39] = {id=39,name="Acid Mist",cost=2,pet="FatsoFargann"},
  [40] = {id=40,name="TP Drainkiss",cost=3,pet="FatsoFargann"},
  [41] = {id=41,name="Roar",cost=2,pet="BlackbeardRandy"},
  [42] = {id=42,name="Razor Fang",cost=1,pet="BlackbeardRandy"},
  [43] = {id=43,name="Claw Cyclone",cost=1,pet="BlackbeardRandy"},
  [44] = {id=44,name="Crossthrash",cost=2,pet="BlackbeardRandy"},
  [45] = {id=45,name="Predatory Glare",cost=2,pet="BlackbeardRandy"},
  [46] = {id=46,name="Tail Blow",cost=1,pet="WarlikePatrick"},
  [47] = {id=47,name="Fireball",cost=1,pet="WarlikePatrick"},
  [48] = {id=48,name="Blockhead",cost=1,pet="WarlikePatrick"},
  [49] = {id=49,name="Brain Crush",cost=1,pet="WarlikePatrick"},
  [50] = {id=50,name="Infrasonics",cost=2,pet="WarlikePatrick"},
  [51] = {id=51,name="Secretion",cost=1,pet="WarlikePatrick"},
  [52] = {id=52,name="Foot Kick",cost=1,pet="PonderingPeter"},
  [53] = {id=53,name="Dust Cloud",cost=1,pet="PonderingPeter"},
  [54] = {id=54,name="Whirl Claws",cost=1,pet="PonderingPeter"},
  [55] = {id=55,name="Wild Carrot",cost=2,pet="PonderingPeter"}
}